name: deploy-book

# Only run this when the main branch changes
on:
  push: 
    branches:
      - main
    paths:
      - CH40208/**

# Define permissions at the top level
permissions:
  contents: read
  pages: write
  id-token: write

# This job installs dependencies, builds the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - uses: actions/checkout@v3

    # Install dependencies
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r CH40208/requirements.txt

    # Build the book
    - name: Build the book
      run: |
        jupyter-book build CH40208/

    # Upload the book's HTML as an artifact
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: "CH40208/_build/html"

    # Configure Pages
    - name: Setup Pages
      uses: actions/configure-pages@v3

    # Push the book's HTML to github-pages
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
